/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tichu;

/**
 *
 * @author matzaflokos
 */
public class Phoenix extends javax.swing.JFrame {

    /**
     * Creates new form Phoenix
     */
    public Phoenix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jB_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix14.jpg")); // NOI18N
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 530, 106, 170));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix11.jpg")); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 330, 106, 170));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix13.jpg")); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 530, 106, 170));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix10.jpg")); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 330, 106, 170));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix9.jpg")); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 330, 106, 170));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix8.jpg")); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 330, 106, 170));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix7.jpg")); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 106, 170));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix6.jpg")); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 130, 106, 170));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix5.jpg")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 130, 106, 170));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix4.jpg")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 130, 106, 170));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix3.jpg")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 130, 106, 170));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix12.jpg")); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 106, 170));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\matzaflokos\\Documents\\NetBeansProjects\\TICHU!\\CardImages\\phoix2.jpg")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 106, 170));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USE PHOENIX AS...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 710, 84));

        jB_OK.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        jB_OK.setText("OK");
        jB_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_OKMouseClicked(evt);
            }
        });
        jPanel1.add(jB_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 565, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        TICHU.input = "2";
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "3";
    }//GEN-LAST:event_jButton2jButton4MouseClicked

    private void jButton3jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "5";
    }//GEN-LAST:event_jButton3jButton4MouseClicked

    private void jButton4jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "4";
    }//GEN-LAST:event_jButton4jButton4MouseClicked

    private void jButton6jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "11";
    }//GEN-LAST:event_jButton6jButton4MouseClicked

    private void jButton7jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "10";
    }//GEN-LAST:event_jButton7jButton4MouseClicked

    private void jButton8jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "6";
    }//GEN-LAST:event_jButton8jButton4MouseClicked

    private void jButton9jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "7";
    }//GEN-LAST:event_jButton9jButton4MouseClicked

    private void jButton10jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "9";
    }//GEN-LAST:event_jButton10jButton4MouseClicked

    private void jButton11jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "8";
    }//GEN-LAST:event_jButton11jButton4MouseClicked

    private void jButton12jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "14";
    }//GEN-LAST:event_jButton12jButton4MouseClicked

    private void jButton13jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "13";
    }//GEN-LAST:event_jButton13jButton4MouseClicked

    private void jButton14jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14jButton4MouseClicked
        // TODO add your handling code here:
        TICHU.input = "12";
        
    }//GEN-LAST:event_jButton14jButton4MouseClicked

    private void jB_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_OKMouseClicked
        // TODO add your handling code here:
        if(TICHU.input != ""){
            TICHU.check = true;
            this.dispose();
        }
    }//GEN-LAST:event_jB_OKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phoenix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phoenix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phoenix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phoenix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phoenix().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
